apiVersion: v1
kind: Service
metadata:
  labels:
    app: contentful
  name: contentful
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: contentful