apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentful
  labels:
    app: contentful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentful
  template:
    metadata:
      labels:
        app: contentful
    spec:
      containers:
        - image: nagaraj1171/contentful:Latest
          name: contentful
          ports:
            - containerPort: 3000
              name: contentful
          volumeMounts:
            - name: contentful-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: contentful-persistent-storage
          persistentVolumeClaim:
            claimName: contentful-volumeclaim